// <auto-generated />
using CookBookAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CookBookAPI.Migrations
{
    [DbContext(typeof(CookBookDbContext))]
    [Migration("20190204220347_new")]
    partial class @new
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CookBookAPI.Models.RecipeIngredients", b =>
                {
                    b.Property<int>("RecipeID");

                    b.Property<int>("IngredientsID");

                    b.Property<int>("Ingredients");

                    b.Property<string>("Quantity")
                        .HasColumnType("varchar(max)");

                    b.Property<int>("Recipes");

                    b.HasKey("RecipeID", "IngredientsID");

                    b.ToTable("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
