// <auto-generated />
using CookBookAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CookBookAPI.Migrations
{
    [DbContext(typeof(CookBookDbContext))]
    [Migration("20190205222119_3seed")]
    partial class _3seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CookBookAPI.Models.Ingredients", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Olive Oil"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Chicken Breast"
                        },
                        new
                        {
                            ID = 3,
                            Name = "White Onion"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Garlic"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Chicken Broth"
                        },
                        new
                        {
                            ID = 6,
                            Name = "White Kidney Beans"
                        },
                        new
                        {
                            ID = 7,
                            Name = "Green Chilies"
                        },
                        new
                        {
                            ID = 8,
                            Name = "Dried Oregano"
                        },
                        new
                        {
                            ID = 9,
                            Name = "Ground Cumin"
                        },
                        new
                        {
                            ID = 10,
                            Name = "Cayenne Pepper"
                        },
                        new
                        {
                            ID = 11,
                            Name = "Fresh Cilanto"
                        },
                        new
                        {
                            ID = 12,
                            Name = "Monterey Jack Cheese"
                        },
                        new
                        {
                            ID = 13,
                            Name = "Salt"
                        },
                        new
                        {
                            ID = 14,
                            Name = "Unsalted Butter"
                        },
                        new
                        {
                            ID = 15,
                            Name = "White Sugar"
                        },
                        new
                        {
                            ID = 16,
                            Name = "Vanilla Extract"
                        },
                        new
                        {
                            ID = 17,
                            Name = "All-Purpose Flour"
                        },
                        new
                        {
                            ID = 18,
                            Name = "Hot Sauce"
                        },
                        new
                        {
                            ID = 19,
                            Name = " Worcestershire Sauce"
                        },
                        new
                        {
                            ID = 20,
                            Name = "White Vinegar"
                        },
                        new
                        {
                            ID = 21,
                            Name = "Celery"
                        },
                        new
                        {
                            ID = 22,
                            Name = "Ground Chicken"
                        },
                        new
                        {
                            ID = 23,
                            Name = "Pork Rinds"
                        },
                        new
                        {
                            ID = 24,
                            Name = "Egg"
                        },
                        new
                        {
                            ID = 25,
                            Name = "Unflavored Gelatin"
                        },
                        new
                        {
                            ID = 26,
                            Name = "Celery Seed"
                        },
                        new
                        {
                            ID = 27,
                            Name = "Blue Cheese"
                        });
                });

            modelBuilder.Entity("CookBookAPI.Models.Instructions", b =>
                {
                    b.Property<int>("RecipeID");

                    b.Property<int>("StepNumberID");

                    b.Property<string>("Action");

                    b.HasKey("RecipeID", "StepNumberID");

                    b.ToTable("Instructions");

                    b.HasData(
                        new
                        {
                            RecipeID = 1,
                            StepNumberID = 1,
                            Action = "Heat olive oil in a Dutch oven over medium heat. Cook chicken, onion, and garlic in hot oil until the chicken is browned completely, 3 to 5 minutes per side."
                        },
                        new
                        {
                            RecipeID = 1,
                            StepNumberID = 2,
                            Action = "Remove the chicken to a cutting board, cut into 1-inch pieces, and return to the Dutch oven; add chicken broth, cannellini, green chilies, oregano, cumin, and cayenne pepper. Bring the mixture to a simmer and cook until the chicken is cooked through, 30 to 45 minutes."
                        },
                        new
                        {
                            RecipeID = 1,
                            StepNumberID = 3,
                            Action = "Divide cilantro among 4 bowls. Ladle chili over cilantro and top with cheese. Season with salt to serve."
                        },
                        new
                        {
                            RecipeID = 2,
                            StepNumberID = 1,
                            Action = "Preheat oven to 350 degrees F (180 degrees C)."
                        },
                        new
                        {
                            RecipeID = 2,
                            StepNumberID = 2,
                            Action = "Cream butter and sugar until fluffy. Stir in vanilla; add flour and mix well."
                        },
                        new
                        {
                            RecipeID = 2,
                            StepNumberID = 3,
                            Action = "Put through cookie press and form cookies onto baking sheets. Bake for 10 - 12 minutes."
                        },
                        new
                        {
                            RecipeID = 3,
                            StepNumberID = 1,
                            Action = "Melt 1 1/2 tablespoons butter in a saucepan over low heat. Add 1 medium clove, minced garlic and cook for about a minute.  Add hot sauce, 1 teaspoon Worcestershire sauce, vinegar, salt and pepper to taste. Whisk to combine then simmer for a bit before setting aside."
                        },
                        new
                        {
                            RecipeID = 3,
                            StepNumberID = 2,
                            Action = "Heat the olive oil for the chicken in a skillet over medium heat. Add the onion, celery, and minced garlic.  Cook until softened then set aside to cool."
                        },
                        new
                        {
                            RecipeID = 3,
                            StepNumberID = 3,
                            Action = "Preheat oven to 375°F. Whisk eggs and chicken stock in a medium bowl. Add the gelatin then allow to bloom for 5 minutes."
                        },
                        new
                        {
                            RecipeID = 3,
                            StepNumberID = 4,
                            Action = "Add chicken, Worcestershire sauce, celery seed, pork rinds, salt, pepper, and 1/4 of the prepared wing sauce to the bowl with the onion mixture. Add the eggs then mix to combine."
                        },
                        new
                        {
                            RecipeID = 3,
                            StepNumberID = 5,
                            Action = "Spray the compartments of a cupcake tin with cooking spray. Add about 2 tablespoons of meatloaf mixture per well, then press a space into the center of each one for the fillings. Add blue cheese and top with a slice of butter. Top with the remaining meat and brush the wing sauce on top. Transfer the tray to the oven and bake. Brush more sauce on top every ten minutes, baking for 25 minutes."
                        });
                });

            modelBuilder.Entity("CookBookAPI.Models.RecipeIngredients", b =>
                {
                    b.Property<int>("RecipeID");

                    b.Property<int>("IngredientsID");

                    b.Property<string>("Quantity")
                        .HasColumnType("varchar(max)");

                    b.HasKey("RecipeID", "IngredientsID");

                    b.HasIndex("IngredientsID");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            RecipeID = 1,
                            IngredientsID = 1,
                            Quantity = "1 tablespoon"
                        },
                        new
                        {
                            RecipeID = 1,
                            IngredientsID = 2,
                            Quantity = "3 skinless, boneless halved"
                        },
                        new
                        {
                            RecipeID = 1,
                            IngredientsID = 3,
                            Quantity = "1 large, chopped"
                        },
                        new
                        {
                            RecipeID = 1,
                            IngredientsID = 4,
                            Quantity = "2 cloves, minced"
                        },
                        new
                        {
                            RecipeID = 1,
                            IngredientsID = 5,
                            Quantity = "5 1/4 cups"
                        },
                        new
                        {
                            RecipeID = 1,
                            IngredientsID = 6,
                            Quantity = "15 oz"
                        },
                        new
                        {
                            RecipeID = 1,
                            IngredientsID = 7,
                            Quantity = "4 oz"
                        },
                        new
                        {
                            RecipeID = 1,
                            IngredientsID = 8,
                            Quantity = "1 tablespoon"
                        },
                        new
                        {
                            RecipeID = 1,
                            IngredientsID = 9,
                            Quantity = "1 teaspoon"
                        },
                        new
                        {
                            RecipeID = 1,
                            IngredientsID = 10,
                            Quantity = "2 pinches"
                        },
                        new
                        {
                            RecipeID = 1,
                            IngredientsID = 11,
                            Quantity = "1/4 cup, chopped"
                        },
                        new
                        {
                            RecipeID = 1,
                            IngredientsID = 12,
                            Quantity = "1/2 cup shredded"
                        },
                        new
                        {
                            RecipeID = 1,
                            IngredientsID = 13,
                            Quantity = "to taste"
                        },
                        new
                        {
                            RecipeID = 2,
                            IngredientsID = 14,
                            Quantity = "2 cups, softened"
                        },
                        new
                        {
                            RecipeID = 2,
                            IngredientsID = 15,
                            Quantity = "1 cup"
                        },
                        new
                        {
                            RecipeID = 2,
                            IngredientsID = 16,
                            Quantity = "2 teaspoons"
                        },
                        new
                        {
                            RecipeID = 2,
                            IngredientsID = 17,
                            Quantity = "4 cups"
                        },
                        new
                        {
                            RecipeID = 3,
                            IngredientsID = 14,
                            Quantity = "4 tablespoons"
                        },
                        new
                        {
                            RecipeID = 3,
                            IngredientsID = 4,
                            Quantity = "3 medium cloves"
                        },
                        new
                        {
                            RecipeID = 3,
                            IngredientsID = 18,
                            Quantity = "2/3 cup"
                        },
                        new
                        {
                            RecipeID = 3,
                            IngredientsID = 19,
                            Quantity = "2 teaspoons"
                        },
                        new
                        {
                            RecipeID = 3,
                            IngredientsID = 20,
                            Quantity = "1 1/2 tablespoons"
                        },
                        new
                        {
                            RecipeID = 3,
                            IngredientsID = 1,
                            Quantity = "1 tablespoon"
                        },
                        new
                        {
                            RecipeID = 3,
                            IngredientsID = 3,
                            Quantity = "1/2 medium, diced"
                        },
                        new
                        {
                            RecipeID = 3,
                            IngredientsID = 21,
                            Quantity = "1 rib, minced"
                        },
                        new
                        {
                            RecipeID = 3,
                            IngredientsID = 22,
                            Quantity = "1 pound"
                        },
                        new
                        {
                            RecipeID = 3,
                            IngredientsID = 23,
                            Quantity = "1/2 cup crushed"
                        },
                        new
                        {
                            RecipeID = 3,
                            IngredientsID = 24,
                            Quantity = "1 large"
                        },
                        new
                        {
                            RecipeID = 3,
                            IngredientsID = 5,
                            Quantity = "2 tablespoons"
                        },
                        new
                        {
                            RecipeID = 3,
                            IngredientsID = 25,
                            Quantity = "1/2 teaspoon"
                        },
                        new
                        {
                            RecipeID = 3,
                            IngredientsID = 26,
                            Quantity = "1/4 teaspoon"
                        },
                        new
                        {
                            RecipeID = 3,
                            IngredientsID = 27,
                            Quantity = "2 ounces"
                        });
                });

            modelBuilder.Entity("CookBookAPI.Models.Recipes", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "White Chicken Chili"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Shortbread Cookies"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Buffalo Chicken Meatloaf Cupcakes"
                        });
                });

            modelBuilder.Entity("CookBookAPI.Models.Instructions", b =>
                {
                    b.HasOne("CookBookAPI.Models.Recipes", "Recipe")
                        .WithMany("InstructionID")
                        .HasForeignKey("RecipeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CookBookAPI.Models.RecipeIngredients", b =>
                {
                    b.HasOne("CookBookAPI.Models.Ingredients", "Ingredient")
                        .WithMany("Recipe")
                        .HasForeignKey("IngredientsID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CookBookAPI.Models.Recipes", "Recipe")
                        .WithMany("IngredientID")
                        .HasForeignKey("RecipeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
