// <auto-generated />
using CookBookAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CookBookAPI.Migrations
{
    [DbContext(typeof(CookBookDbContext))]
    partial class CookBookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CookBookAPI.Models.Ingredients", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Olive Oil"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Chicken Breast"
                        },
                        new
                        {
                            ID = 3,
                            Name = "White Onion"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Garlic"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Chicken Broth"
                        },
                        new
                        {
                            ID = 6,
                            Name = "White Kidney Beans"
                        },
                        new
                        {
                            ID = 7,
                            Name = "Green Chilies"
                        },
                        new
                        {
                            ID = 8,
                            Name = "Dried Oregano"
                        },
                        new
                        {
                            ID = 9,
                            Name = "Ground Cumin"
                        },
                        new
                        {
                            ID = 10,
                            Name = "Cayenne Pepper"
                        },
                        new
                        {
                            ID = 11,
                            Name = "Fresh Cilanto"
                        },
                        new
                        {
                            ID = 12,
                            Name = "Monterey Jack Cheese"
                        },
                        new
                        {
                            ID = 13,
                            Name = "Salt"
                        },
                        new
                        {
                            ID = 14,
                            Name = "Unsalted Butter"
                        },
                        new
                        {
                            ID = 15,
                            Name = "White Sugar"
                        },
                        new
                        {
                            ID = 16,
                            Name = "Vanilla Extract"
                        },
                        new
                        {
                            ID = 17,
                            Name = "All-Purpose Flour"
                        },
                        new
                        {
                            ID = 18,
                            Name = "Hot Sauce"
                        },
                        new
                        {
                            ID = 19,
                            Name = " Worcestershire Sauce"
                        },
                        new
                        {
                            ID = 20,
                            Name = "White Vinegar"
                        },
                        new
                        {
                            ID = 21,
                            Name = "Celery"
                        },
                        new
                        {
                            ID = 22,
                            Name = "Ground Chicken"
                        },
                        new
                        {
                            ID = 23,
                            Name = "Pork Rinds"
                        },
                        new
                        {
                            ID = 24,
                            Name = "Egg"
                        },
                        new
                        {
                            ID = 25,
                            Name = "Unflavored Gelatin"
                        },
                        new
                        {
                            ID = 26,
                            Name = "Celery Seed"
                        },
                        new
                        {
                            ID = 27,
                            Name = "Blue Cheese"
                        },
                        new
                        {
                            ID = 28,
                            Name = "Elbow Pasta"
                        },
                        new
                        {
                            ID = 29,
                            Name = "Unsalted Butter"
                        },
                        new
                        {
                            ID = 30,
                            Name = "All Purpose Flour"
                        },
                        new
                        {
                            ID = 31,
                            Name = "Whole Milk"
                        },
                        new
                        {
                            ID = 32,
                            Name = "Half and Half"
                        },
                        new
                        {
                            ID = 33,
                            Name = "Medium Sharp Cheddar Cheese"
                        },
                        new
                        {
                            ID = 34,
                            Name = "Gruyere Cheese"
                        },
                        new
                        {
                            ID = 35,
                            Name = "Black Pepper"
                        },
                        new
                        {
                            ID = 36,
                            Name = "Paprika"
                        },
                        new
                        {
                            ID = 37,
                            Name = "Baking Powder"
                        },
                        new
                        {
                            ID = 38,
                            Name = "Granulated Sugar"
                        });
                });

            modelBuilder.Entity("CookBookAPI.Models.Instructions", b =>
                {
                    b.Property<int>("RecipeID");

                    b.Property<int>("StepNumberID");

                    b.Property<string>("Action");

                    b.HasKey("RecipeID", "StepNumberID");

                    b.ToTable("Instructions");

                    b.HasData(
                        new
                        {
                            RecipeID = 1,
                            StepNumberID = 1,
                            Action = "Heat olive oil in a Dutch oven over medium heat. Cook chicken, onion, and garlic in hot oil until the chicken is browned completely, 3 to 5 minutes per side."
                        },
                        new
                        {
                            RecipeID = 1,
                            StepNumberID = 2,
                            Action = "Remove the chicken to a cutting board, cut into 1-inch pieces, and return to the Dutch oven; add chicken broth, cannellini, green chilies, oregano, cumin, and cayenne pepper. Bring the mixture to a simmer and cook until the chicken is cooked through, 30 to 45 minutes."
                        },
                        new
                        {
                            RecipeID = 1,
                            StepNumberID = 3,
                            Action = "Divide cilantro among 4 bowls. Ladle chili over cilantro and top with cheese. Season with salt to serve."
                        },
                        new
                        {
                            RecipeID = 2,
                            StepNumberID = 1,
                            Action = "Preheat oven to 350 degrees F (180 degrees C)."
                        },
                        new
                        {
                            RecipeID = 2,
                            StepNumberID = 2,
                            Action = "Cream butter and sugar until fluffy. Stir in vanilla; add flour and mix well."
                        },
                        new
                        {
                            RecipeID = 2,
                            StepNumberID = 3,
                            Action = "Put through cookie press and form cookies onto baking sheets. Bake for 10 - 12 minutes."
                        },
                        new
                        {
                            RecipeID = 3,
                            StepNumberID = 1,
                            Action = "Melt 1 1/2 tablespoons butter in a saucepan over low heat. Add 1 medium clove, minced garlic and cook for about a minute.  Add hot sauce, 1 teaspoon Worcestershire sauce, vinegar, salt and pepper to taste. Whisk to combine then simmer for a bit before setting aside."
                        },
                        new
                        {
                            RecipeID = 3,
                            StepNumberID = 2,
                            Action = "Heat the olive oil for the chicken in a skillet over medium heat. Add the onion, celery, and minced garlic.  Cook until softened then set aside to cool."
                        },
                        new
                        {
                            RecipeID = 3,
                            StepNumberID = 3,
                            Action = "Preheat oven to 375°F. Whisk eggs and chicken stock in a medium bowl. Add the gelatin then allow to bloom for 5 minutes."
                        },
                        new
                        {
                            RecipeID = 3,
                            StepNumberID = 4,
                            Action = "Add chicken, Worcestershire sauce, celery seed, pork rinds, salt, pepper, and 1/4 of the prepared wing sauce to the bowl with the onion mixture. Add the eggs then mix to combine."
                        },
                        new
                        {
                            RecipeID = 3,
                            StepNumberID = 5,
                            Action = "Spray the compartments of a cupcake tin with cooking spray. Add about 2 tablespoons of meatloaf mixture per well, then press a space into the center of each one for the fillings. Add blue cheese and top with a slice of butter. Top with the remaining meat and brush the wing sauce on top. Transfer the tray to the oven and bake. Brush more sauce on top every ten minutes, baking for 25 minutes."
                        },
                        new
                        {
                            RecipeID = 4,
                            StepNumberID = 1,
                            Action = "Preheat oven to 325 degrees F and grease a 3 qt baking dish (9x13). Set aside."
                        },
                        new
                        {
                            RecipeID = 4,
                            StepNumberID = 2,
                            Action = "Bring a large pot of salted water to a boil.  When boiling, add dried pasta and cook 1 minute less than the package directs for al dente.  Drain and drizzle with a little bit of olive oil to keep from sticking."
                        },
                        new
                        {
                            RecipeID = 4,
                            StepNumberID = 3,
                            Action = "While water is coming up to a boil, grate cheeses and toss together to mix, then divide into three piles.  Approximately 3 cups for the sauce, 1 1/2 cups for the inner layer, and 1 1/2 cups for the topping."
                        },
                        new
                        {
                            RecipeID = 4,
                            StepNumberID = 4,
                            Action = "Melt butter in a large saucepan over MED heat.  Sprinkle in flour and whisk to combine.  Mixture will look like very wet sand.  Cook for approximately 1 minute, whisking often.  Slowly pour in about 2 cups or so of the milk/half and half, while whisking constantly, until smooth.  Slowly pour in the remaining milk/half and half, while whisking constantly, until combined and smooth."
                        },
                        new
                        {
                            RecipeID = 4,
                            StepNumberID = 5,
                            Action = "Continue to heat over MED heat, whisking very often, until thickened to a very thick consistency.  It should almost be the consistency of a semi thinned out condensed soup."
                        },
                        new
                        {
                            RecipeID = 4,
                            StepNumberID = 6,
                            Action = "Stir in spices and 1 1/2 cups of the cheeses, stirring to melt and combine.  Stir in another 1 1/2 cups of cheese, and stir until completely melted and smooth."
                        },
                        new
                        {
                            RecipeID = 4,
                            StepNumberID = 7,
                            Action = "In a large mixing bowl, combine drained pasta with cheese sauce, stirring to combine fully.  Pour half of the pasta mixture into the prepared baking dish.  Top with 1 1/2 cups of grated cheeses, then top that with the remaining pasta mixture."
                        },
                        new
                        {
                            RecipeID = 4,
                            StepNumberID = 8,
                            Action = "Sprinkle the top with the last 1 1/2 cups of cheese and bake for 15 minutes, until cheesy is bubbly and lightly golden brown."
                        },
                        new
                        {
                            RecipeID = 5,
                            StepNumberID = 1,
                            Action = "Stir together flour, baking powder, sugar, and salt in medium size bowl. Cut in butter until crumbly. Stir in milk to make a soft dough."
                        },
                        new
                        {
                            RecipeID = 5,
                            StepNumberID = 2,
                            Action = "Drop by spoonfuls into boiling stew. Cover and simmer 15 minutes without lifting lid. Serve."
                        },
                        new
                        {
                            RecipeID = 5,
                            StepNumberID = 3,
                            Action = "To make parsley dumplings, add 1 tablespoon parsley flakes to the dry ingredients."
                        });
                });

            modelBuilder.Entity("CookBookAPI.Models.RecipeIngredients", b =>
                {
                    b.Property<int>("RecipeID");

                    b.Property<int>("IngredientsID");

                    b.Property<string>("Quantity")
                        .HasColumnType("varchar(max)");

                    b.HasKey("RecipeID", "IngredientsID");

                    b.HasIndex("IngredientsID");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            RecipeID = 1,
                            IngredientsID = 1,
                            Quantity = "1 tablespoon"
                        },
                        new
                        {
                            RecipeID = 1,
                            IngredientsID = 2,
                            Quantity = "3 skinless, boneless halved"
                        },
                        new
                        {
                            RecipeID = 1,
                            IngredientsID = 3,
                            Quantity = "1 large, chopped"
                        },
                        new
                        {
                            RecipeID = 1,
                            IngredientsID = 4,
                            Quantity = "2 cloves, minced"
                        },
                        new
                        {
                            RecipeID = 1,
                            IngredientsID = 5,
                            Quantity = "5 1/4 cups"
                        },
                        new
                        {
                            RecipeID = 1,
                            IngredientsID = 6,
                            Quantity = "15 oz"
                        },
                        new
                        {
                            RecipeID = 1,
                            IngredientsID = 7,
                            Quantity = "4 oz"
                        },
                        new
                        {
                            RecipeID = 1,
                            IngredientsID = 8,
                            Quantity = "1 tablespoon"
                        },
                        new
                        {
                            RecipeID = 1,
                            IngredientsID = 9,
                            Quantity = "1 teaspoon"
                        },
                        new
                        {
                            RecipeID = 1,
                            IngredientsID = 10,
                            Quantity = "2 pinches"
                        },
                        new
                        {
                            RecipeID = 1,
                            IngredientsID = 11,
                            Quantity = "1/4 cup, chopped"
                        },
                        new
                        {
                            RecipeID = 1,
                            IngredientsID = 12,
                            Quantity = "1/2 cup shredded"
                        },
                        new
                        {
                            RecipeID = 1,
                            IngredientsID = 13,
                            Quantity = "to taste"
                        },
                        new
                        {
                            RecipeID = 2,
                            IngredientsID = 14,
                            Quantity = "2 cups, softened"
                        },
                        new
                        {
                            RecipeID = 2,
                            IngredientsID = 15,
                            Quantity = "1 cup"
                        },
                        new
                        {
                            RecipeID = 2,
                            IngredientsID = 16,
                            Quantity = "2 teaspoons"
                        },
                        new
                        {
                            RecipeID = 2,
                            IngredientsID = 17,
                            Quantity = "4 cups"
                        },
                        new
                        {
                            RecipeID = 3,
                            IngredientsID = 14,
                            Quantity = "4 tablespoons"
                        },
                        new
                        {
                            RecipeID = 3,
                            IngredientsID = 4,
                            Quantity = "3 medium cloves"
                        },
                        new
                        {
                            RecipeID = 3,
                            IngredientsID = 18,
                            Quantity = "2/3 cup"
                        },
                        new
                        {
                            RecipeID = 3,
                            IngredientsID = 19,
                            Quantity = "2 teaspoons"
                        },
                        new
                        {
                            RecipeID = 3,
                            IngredientsID = 20,
                            Quantity = "1 1/2 tablespoons"
                        },
                        new
                        {
                            RecipeID = 3,
                            IngredientsID = 1,
                            Quantity = "1 tablespoon"
                        },
                        new
                        {
                            RecipeID = 3,
                            IngredientsID = 3,
                            Quantity = "1/2 medium, diced"
                        },
                        new
                        {
                            RecipeID = 3,
                            IngredientsID = 21,
                            Quantity = "1 rib, minced"
                        },
                        new
                        {
                            RecipeID = 3,
                            IngredientsID = 22,
                            Quantity = "1 pound"
                        },
                        new
                        {
                            RecipeID = 3,
                            IngredientsID = 23,
                            Quantity = "1/2 cup crushed"
                        },
                        new
                        {
                            RecipeID = 3,
                            IngredientsID = 24,
                            Quantity = "1 large"
                        },
                        new
                        {
                            RecipeID = 3,
                            IngredientsID = 5,
                            Quantity = "2 tablespoons"
                        },
                        new
                        {
                            RecipeID = 3,
                            IngredientsID = 25,
                            Quantity = "1/2 teaspoon"
                        },
                        new
                        {
                            RecipeID = 3,
                            IngredientsID = 26,
                            Quantity = "1/4 teaspoon"
                        },
                        new
                        {
                            RecipeID = 3,
                            IngredientsID = 27,
                            Quantity = "2 ounces"
                        },
                        new
                        {
                            RecipeID = 4,
                            IngredientsID = 28,
                            Quantity = "1 pound"
                        },
                        new
                        {
                            RecipeID = 4,
                            IngredientsID = 29,
                            Quantity = "1 stick"
                        },
                        new
                        {
                            RecipeID = 4,
                            IngredientsID = 30,
                            Quantity = "1/2 cup"
                        },
                        new
                        {
                            RecipeID = 4,
                            IngredientsID = 31,
                            Quantity = "1 and 1/2 cups"
                        },
                        new
                        {
                            RecipeID = 4,
                            IngredientsID = 32,
                            Quantity = "2 and 1/2 cups"
                        },
                        new
                        {
                            RecipeID = 4,
                            IngredientsID = 33,
                            Quantity = "4 cups grated"
                        },
                        new
                        {
                            RecipeID = 4,
                            IngredientsID = 34,
                            Quantity = "2 cups grated"
                        },
                        new
                        {
                            RecipeID = 4,
                            IngredientsID = 13,
                            Quantity = "1/2 tbsp"
                        },
                        new
                        {
                            RecipeID = 4,
                            IngredientsID = 35,
                            Quantity = "1/2 tsp"
                        },
                        new
                        {
                            RecipeID = 4,
                            IngredientsID = 36,
                            Quantity = "1/4 tsp"
                        },
                        new
                        {
                            RecipeID = 5,
                            IngredientsID = 17,
                            Quantity = "1 cup"
                        },
                        new
                        {
                            RecipeID = 5,
                            IngredientsID = 37,
                            Quantity = "2 tsp"
                        },
                        new
                        {
                            RecipeID = 5,
                            IngredientsID = 38,
                            Quantity = "1 tsp"
                        },
                        new
                        {
                            RecipeID = 5,
                            IngredientsID = 13,
                            Quantity = "1/2 tsp"
                        },
                        new
                        {
                            RecipeID = 5,
                            IngredientsID = 14,
                            Quantity = "1 tbsp"
                        },
                        new
                        {
                            RecipeID = 5,
                            IngredientsID = 31,
                            Quantity = "1/2 cup"
                        });
                });

            modelBuilder.Entity("CookBookAPI.Models.Recipes", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageURL");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ImageURL = "https://lh3.googleusercontent.com/t6E4pJFAevAGqReny5IrPYOAw0CQzM2ntvjqbdARtE0MHBOrOPgcFYCKm-25YQ0o45tCF-Fv6HAqoWr03g_QSXDfGs1qMRsfeXeGKM4OKWoz3L850SN8wihPYKGFMEjQCdNox5ZHkCMXKX2iwQire-h6cG_w1PrVyUkKXJqKN7q5bRRb-yQ70a_ALCcWLYttlBJl-MB_CGoXE_KpuV6wTsPYt1sWzhwUo-rrx97QT-QcTu1OIF1VxVxDTnkNE-U8yRWV6ONjJT1qzZx1j4ek8mEEUGhLQuCfSYMbR-3wPlDHtbWS2Kk4TJMyj6E08rslaFQh6xoHcLlGFrsEz4Iao26aUMLYU-WMWTuNHTwU8T2jfYin40VrUgtjaRX9SpPurdlaGR2bIWnu09rw-9FYLCneabM5Ok56AqxucR2pairb6NBMifNevr6_aErXx2SkWaDatsrUHbmlMupI5xZOikPPSAKbyg2AXzZY9tuBT4oM4HZG_20jXs8VK5j8xD4L6-6Zc4srak9hPgBexhB0to4ODG7-JEA4BHfAB0E8Rvfm9mxhUYbF2-lWGuHM1kj_ZNqsz9K97EtfReQ5jFn61ASD7mlcABdaNfsKaRbcy6u-2fqYbdvHBOcn0bUvc5woTM7T7rHym4nDdSZ_CKADzr4-C9oAWWRjPDY13LaRpqNDKmGHcXq3Mc5giQvlR6k4Bo7Q10pFrdJ66yYLG5U4RuG6=w600-h900-no",
                            Name = "White Chicken Chili"
                        },
                        new
                        {
                            ID = 2,
                            ImageURL = "https://lh3.googleusercontent.com/ZtSoWRoG4_ZVEPcSYcBmFDT6PUrMP7Rc5uhMRKPurDKdHK9n4CHw0YGFfWMKnH0viBqTdlGijYsPkXw4doWEtQxuwa7e1Sun7p4Uzto1KGwQBGc0taM3Fe61mYpdW7dTHRBcR_mkDtZOn8ByjQq8oQA9yY3gVAxev3qMNzFvHlCfVdEx3UfmDh-ymuip0dRNyscf8-vwUd-sSoqUe-4H5lNjWNTp7dvIot7jcSZ3AMkbgCcikE8u-CsyhTTHzb4RPqVyQkfG214wXcmA6CicPCA2WTn5idRmSP7crWx7HVR1fsF3OS-L4_IVCVCppsZloDqHwk3EFhb7xcBWlFO8iKFND4cUjq-ArKU7vr4WbAEPrEZk4nWo08MZKXP3-pkSdZ0D8FlTuBvC4vqyYv75_Gj1rDAGPxMMjexfDMDB47czoaxUWWyNvWs5OZPATHEP_XG6mqK3Boh_ZZn9KgodXsLkxPZ4DmB58xJMcS0HfzsYHKIkoEoN9fQhvYDVwMePYinR4_A_lVoWg8wtXuwjoFyMsUzSQvRapLV5BV7Jo11rrNBv8NJJCke7rINwNkBtt0pVK-Jb-YstRWhU-MVGix7TjHCYE7bHzgNoQG9h-2AinYNGHkBrk1I4xuOP1aZCUYspr0ArJlEzyRFdJ2wQvR1hjWgsPV1MHAQIs4GUNrXsragrvmDq9FAbaSF3mybvi9MHXFPSiP58ID6kcGe3nsQX=w689-h915-no",
                            Name = "Shortbread Cookies"
                        },
                        new
                        {
                            ID = 3,
                            ImageURL = "https://goo.gl/images/JkTjTQ",
                            Name = "Buffalo Chicken Meatloaf Cupcakes"
                        },
                        new
                        {
                            ID = 4,
                            ImageURL = "https://goo.gl/images/MNwsmA",
                            Name = "Baked Mac N Cheese"
                        },
                        new
                        {
                            ID = 5,
                            ImageURL = "https://images.media-allrecipes.com/userphotos/720x405/5011529.jpg",
                            Name = "Dumplings"
                        });
                });

            modelBuilder.Entity("CookBookAPI.Models.Instructions", b =>
                {
                    b.HasOne("CookBookAPI.Models.Recipes", "Recipe")
                        .WithMany("InstructionID")
                        .HasForeignKey("RecipeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CookBookAPI.Models.RecipeIngredients", b =>
                {
                    b.HasOne("CookBookAPI.Models.Ingredients", "Ingredient")
                        .WithMany("Recipe")
                        .HasForeignKey("IngredientsID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CookBookAPI.Models.Recipes", "Recipe")
                        .WithMany("IngredientID")
                        .HasForeignKey("RecipeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
